### PR TITLE
Add name to list-of-users.txt and Add new folder to personal

### PR DESCRIPTION
**Pull request by yarynayavor**

### CODE REVIEW

**Comment by itspoma** [comment]
@yarynayavor conflicts :)

**Comment by itspoma** [comment]
@yaroslavguk  conflicts again due to merged another PR (pull-request)

**Comment by yarynayavor** [comment]
@itspoma fixed again

**Comment by itspoma** [comment]
@yarynayavor other PR was merged, so new conflicts appears

**Comment by yarynayavor** [comment]
@itspoma fixed again. what about know?

**Pull request merged**
