### PR TITLE
edit list-of-users and created new folder in personal

### PR DESCRIPTION
**Pull request by VasylKhoroshcho**

### CODE REVIEW

**Comment by itspoma** [comment]
@VasylKhoroshcho conflicts :)

**Comment by VasylKhoroshcho** [comment]
Fixed conflict. Waiting for confirming

**Comment by itspoma** [comment]
@VasylKhoroshcho conflicts again due to merged another PR (pull-request)

**Comment by VasylKhoroshcho** [comment]
@itspoma Fixed again)

**Pull request merged**
